name: build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Descomprimir y buscar
        run: |
          unzip -o Slowthv7-3105-2.0-source.zip
          ls -la
          echo "--- PROYECTOS ---"
          find. -name "*.xcodeproj"

      - name: Compilar IPA
        run: |
          PROJ=$(find. -name "*.xcodeproj" | head -n 1)
          echo "Proyecto encontrado: $PROJ"

          xcodebuild -project "$PROJ" \
            -scheme ThreeOneOSFive \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            SYMROOT=$(pwd)/build build

          APP=$(find./build -name "*.app" | head -n 1)
          echo "App: $APP"
          mkdir -p Payload
          cp -R "$APP" Payload/
          zip -r azul.ipa Payload

      - name: Subir IPA
        uses: actions/upload-artifact@v4
        with:
          name: IPA-AZUL-3105
          path: azul.ipa
